name: Java deploy with Maven

on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Deploy with Maven
      run: |
        echo "token:"
        echo ${env.maven_access_token}
      env:
          github_repository_owner: ${{ github.repository_owner }} 
          github_repository_name: ${{ github.event.repository.name }}
          maven_access_user: ${{ secrets.MAVEN_DEPLOY_USER }}
          maven_access_token: ${{ secrets.GITHUB_TOKEN }}
